export const buildStatusItems = (stats, streakCount, t) => [
  {
    key: 'studyDays',
    label: t('ext_1487'),
    value: stats.studyDays,
    unit: t('ext_1'),
    imgSrc: '/assets/images/icons/icon_study_days.webp',
    bg: 'bg-[#EEF2FF]/60',
    bgDark: 'bg-indigo-950/20',
    border: 'border-indigo-100/60',
    borderDark: 'border-indigo-900/30',
    iconBorder: 'border-indigo-100/30',
  },
  {
    key: 'streak',
    label: t('ext_1488'),
    value: streakCount,
    unit: t('ext_1'),
    imgSrc: '/assets/images/icons/icon_streak.webp',
    bg: 'bg-[#FFF0E6]/60',
    bgDark: 'bg-orange-950/20',
    border: 'border-orange-100/60',
    borderDark: 'border-orange-900/40',
    iconBorder: 'border-orange-100/30',
  },
  {
    key: 'accuracy',
    label: t('ext_972'),
    value: stats.accuracy !== null ? `${stats.accuracy}%` : '-',
    unit: '',
    imgSrc: '/assets/images/icons/icon_accuracy.webp',
    bg: 'bg-[#FFFBEB]/60',
    bgDark: 'bg-amber-950/20',
    border: 'border-amber-100/60',
    borderDark: 'border-amber-900/40',
    iconBorder: 'border-amber-100/30',
  },
  {
    key: 'totalActivities',
    label: t('ext_1365'),
    value: stats.totalActivities,
    unit: t('ext_175'),
    imgSrc: '/assets/images/icons/icon_activity.webp',
    bg: 'bg-[#F5F3FF]/70',
    bgDark: 'bg-purple-950/20',
    border: 'border-purple-100/60',
    borderDark: 'border-purple-900/30',
    iconBorder: 'border-purple-100/30',
  },
];
