const pickProps = (source, keys) => keys.reduce((props, key) => {
  props[key] = source[key];
  return props;
}, {});

const ROUTER_PROP_KEYS = [
  'activeStage',
  'addBonusXp',
  'addMainSeenWords',
  'addTodayStat',
  'archivedCompletedDay',
  'authSignOut',
  'backToMain',
  'clearWordWrong',
  'clearWrong',
  'clearedHanjaIds',
  'completedDay',
  'currentDay',
  'currentDayHanjaIds',
  'currentLevel',
  'currentScreen',
  'doneCount',
  'effectivePool',
  'finalJourney',
  'getNextHanjaIds',
  'getNextWordIds',
  'getRewardPreview',
  'gradeSentenceCount',
  'gradeTestBackScreen',
  'gradeWordCount',
  'handleHanjaAcquired',
  'hanjaData',
  'isDarkMode',
  'isJourneyComplete',
  'isPremium',
  'isRestoring',
  'journeyRound',
  'linkIdentity',
  'logCorrectWord',
  'logHanja',
  'logWrongWord',
  'markCorrect',
  'markSeen',
  'markWordCorrect',
  'markWordWrong',
  'markWrong',
  'missions',
  'openMemoryVaultSignal',
  'restoreFromCloud',
  'selectedCharacter',
  'selectedDashboardGrade',
  'selectedGrade',
  'selectedPastStage',
  'sessionReviewPool',
  'setCurrentScreen',
  'setGradeTestBackScreen',
  'setIsDarkMode',
  'setSelectedCharacter',
  'setSelectedDashboardGrade',
  'setSelectedGrade',
  'setSelectedPastStage',
  'setSessionDoneToday',
  'setSessionReviewPool',
  'setShowLoginModal',
  'setShowNewJourneyModal',
  'setShowPremiumModal',
  'setUnlockedPack',
  'setUserNickname',
  'setWriteTargetHanja',
  'streak',
  'totalStats',
  'unlockedPack',
  'updateMissionProgress',
  'user',
  'userNickname',
  'userXp',
  'wordData',
  'writeTargetHanja',
];

const CONTENT_FLOW_PROP_KEYS = [
  'activateReferralForDailyClear',
  'addBonusXp',
  'advanceDay',
  'checkAndShowMissionToast',
  'claimFinalJourney',
  'currentDay',
  'doneCount',
  'finalJourney',
  'getRewardPreview',
  'handleHanjaAcquired',
  'hanjaData',
  'journeyRound',
  'logCorrectWord',
  'logHanja',
  'logWrongWord',
  'logWord',
  'markCorrect',
  'markSeen',
  'markWordCorrect',
  'markWordWrong',
  'markWrong',
  'onboardingDone',
  'routerProps',
  'selectedCharacter',
  'sessionDoneToday',
  'sessionMissions',
  'setCurrentScreen',
  'setOnboardingDone',
  'setSelectedCharacter',
  'setSessionDoneToday',
  'setShowNewJourneyModal',
  'setShowSaveModal',
  'setUserNickname',
  'unlockedPack',
  'updateMissionProgress',
  'userNickname',
  'userRef',
  'userXp',
  'wordData',
];

const OVERLAY_PROP_KEYS = [
  'accountChoiceBusy',
  'accountDataChoice',
  'charToast',
  'currentDay',
  'dismissToast',
  'gradeTestAlert',
  'handleContinueWithoutLink',
  'handleStartNewJourney',
  'handleUsePreviousLogin',
  'isInRankSoonZone',
  'isJourneyComplete',
  'journeyRound',
  'nextRankAvatar',
  'platform',
  'referralOffer',
  'restoreFromCloud',
  'selectedCharacter',
  'setCharToast',
  'setCurrentScreen',
  'setGradeTestAlert',
  'setReferralOffer',
  'setShowLoginModal',
  'setShowNewJourneyModal',
  'setShowPremiumModal',
  'setShowRankUpModal',
  'setShowSaveModal',
  'setUnlockedPack',
  'showLoginModal',
  'showNewJourneyModal',
  'showPremiumModal',
  'showRankUpModal',
  'showSaveModal',
  'signInWithApple',
  'signInWithGoogle',
  'signInWithKakao',
  'streak',
  'user',
  'userXp',
];

export const buildRouterProps = (state) => pickProps(state, ROUTER_PROP_KEYS);

export const buildContentFlowProps = (state) => pickProps(state, CONTENT_FLOW_PROP_KEYS);

export const buildOverlayProps = (state) => ({
  ...pickProps(state, OVERLAY_PROP_KEYS),
  onBrowseJourneyMemory: state.handleBrowseJourneyMemory,
});
