export const SK = {
    USER_XP:              'user_xp',
    ONBOARDING_DONE:      'onboarding_done',
    DARK_MODE:            'dark_mode',
    SELECTED_CHARACTER:   'selected_character',
    USER_NICKNAME:        'user_nickname',
    TODAY_STATS:          'today_stats',
    XP_BUFF_EXPIRES:      'xp_buff_expires',
    TOTAL_ACTIVITY_STATS: 'total_activity_stats',
    LEVEL_TEST_BONUS:     'level_test_bonus',
    LEVEL_TEST_DAILY:     'level_test_daily',
    PREMIUM:              'premium',
    DAILY_SESSION:        'daily_session',
    START_GRADE:          'start_grade',
    MISSION_HISTORY:      'mission_history',
    HANJA_LANG:           'hanja_lang',
    BGM_ON:               'hangul_bgm_on',
    SFX_ON:               'hangul_sfx_on',
    BGM_VOLUME:           'hangul_bgm_volume',
    SFX_VOLUME:           'hangul_sfx_volume',
    VIBRATION:            'hangul_vibration',
    SETTINGS_NICKNAME:    'hangul_user_nickname',
    DEVICE_ID:            'device_id',
    RECORDS:              'hanja_records',
    UNLOCKED_GRADE:       'unlocked_grade',
    MAIN_SEEN_WORDS:      'main_seen_words',
    DAILY_STUDY_LOG:      'daily_study_log',
};
